INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Afghanistan','Kabul');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Albania','Tirana');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Algeria','Algiers');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Andorra','Andorra la Vella');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Angola','Luanda');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Antigua and Barbuda','Saint John\'s');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Argentina','Buenos Aires');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Armenia','Yerevan');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Australia','Canberra');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Austria','Vienna');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Azerbaijan','Baku');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bahamas','Nassau');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bahrain','Manama');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bangladesh','Dhaka');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Barbados','Bridgetown');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Belarus','Minsk');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Belgium','Brussels');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Belize','Belmopan');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Benin','Porto-Novo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bhutan','Thimphu');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bolivia','Sucre (de jure),\nLa Paz (seat of government)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bosnia and Herzegovina','Sarajevo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Botswana','Gaborone');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Brazil','Brasilia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Brunei','Bandar Seri Begawan');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Bulgaria','Sofia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Burkina Faso','Ouagadougou');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Burundi','Bujumbura');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cabo Verde','Praia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cambodia','Phnom Penh');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cameroon','Yaounde');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Canada','Ottawa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Central African Republic','Bangui');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Chad','N\'Djamena');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Chile','Santiago');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('China','Beijing');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Colombia','Bogotá');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Comoros','Moroni');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Democratic Republic of the Congo','Kinshasa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Republic of the Congo','Brazzaville');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Costa Rica','San Jose');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cote d\'Ivoire','Yamoussoukro');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Croatia','Zagreb');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cuba','Havana');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Cyprus','Nicosia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Czech Republic','Prague');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Denmark','Copenhagen');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Djibouti','Djibouti (city)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Dominica','Roseau');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Dominican Republic','Santo Domingo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Ecuador','Quito');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Egypt','Cairo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('El Salvador','San Salvador');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Equatorial Guinea','Malabo (de jure),\nOyala (seat of government)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Eritrea','Asmara');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Estonia','Tallinn');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Ethiopia','Addis Ababa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Fiji','Suva');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Finland','Helsinki');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('France','Paris');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Gabon','Libreville');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Gambia','Banjul');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Georgia','Tbilisi');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Germany','Berlin');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Ghana','Accra');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Greece','Athens');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Grenada','Saint George\'s');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Guatemala','Guatemala City');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Guinea','Conakry');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Guinea-Bissau','Bissau');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Guyana','Georgetown');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Haiti','Port-au-Prince');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Honduras','Tegucigalpa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Hungary','Budapest');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Iceland','Reykjavik');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('India','New Delhi');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Indonesia','Jakarta');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Iran','Tehran');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Iraq','Baghdad');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Ireland','Dublin');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Israel','Jerusalem');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Italy','Rome');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Jamaica','Kingston');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Japan','Tokyo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Jordan','Amman');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kazakhstan','Astana');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kenya','Nairobi');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kiribati','Tarawa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kosovo','Pristina');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kuwait','Kuwait City');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Kyrgyzstan','Bishkek');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Laos','Vientiane');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Latvia','Riga');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Lebanon','Beirut');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Lesotho','Maseru');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Liberia','Monrovia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Libya','Tripoli');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Liechtenstein','Vaduz');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Lithuania','Vilnius');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Luxembourg','Luxembourg (city)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Macedonia (FYROM)','Skopje');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Madagascar','Antananarivo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Malawi','Lilongwe');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Malaysia','Kuala Lumpur');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Maldives','Male');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mali','Bamako');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Malta','Valletta');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Marshall Islands','Majuro');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mauritania','Nouakchott');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mauritius','Port Louis');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mexico','Mexico City');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Micronesia','Palikir');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Moldova','Chisinau');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Monaco','Monaco');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mongolia','Ulaanbaatar');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Montenegro','Podgorica');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Morocco','Rabat');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Mozambique','Maputo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Myanmar (Burma)','Naypyidaw');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Namibia','Windhoek');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Nauru','Yaren District (de facto)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Nepal','Kathmandu');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Netherlands','Amsterdam');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('New Zealand','Wellington');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Nicaragua','Managua');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Niger','Niamey');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Nigeria','Abuja');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('North Korea','Pyongyang');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Norway','Oslo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Oman','Muscat');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Pakistan','Islamabad');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Palau','Ngerulmud');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Palestine','Jerusalem (East)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Panama','Panama City');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Papua New Guinea','Port Moresby');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Paraguay','Asunción');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Peru','Lima');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Philippines','Manila');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Poland','Warsaw');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Portugal','Lisbon');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Qatar','Doha');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Romania','Bucharest');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Russia','Moscow');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Rwanda','Kigali');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Saint Kitts and Nevis','Basseterre');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Saint Lucia','Castries');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Saint Vincent and the Grenadines','Kingstown');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Samoa','Apia');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('San Marino','San Marino');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Sao Tome and Principe','São Tomé');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Saudi Arabia','Riyadh');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Senegal','Dakar');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Serbia','Belgrade');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Seychelles','Victoria');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Sierra Leone','Freetown');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Singapore','Singapore');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Slovakia','Bratislava');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Slovenia','Ljubljana');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Solomon Islands','Honiara');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Somalia','Mogadishu');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('South Africa','Pretoria (administrative),\nCape Town (legislative),\nBloemfontein (judicial)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('South Korea','Seoul');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('South Sudan','Juba');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Spain','Madrid');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Sri Lanka','Sri Jayawardenepura Kotte');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Sudan','Khartoum');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Suriname','Paramaribo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Swaziland','Mbabane (administrative),\nLobamba (legislative, royal)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Sweden','Stockholm');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Switzerland','Bern');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Syria','Damascus');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Taiwan','Taipei');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Tajikistan','Dushanbe');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Tanzania','Dodoma');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Thailand','Bangkok');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Timor-Leste','Dili');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Togo','Lomé');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Tonga','Nukualofa');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Trinidad and Tobago','Port of Spain');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Tunisia','Tunis');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Turkey','Ankara');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Turkmenistan','Ashgabat');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Tuvalu','Funafuti');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Uganda','Kampala');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Ukraine','Kyiv (also known as Kiev)');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('United Arab Emirates','Abu Dhabi');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('United Kingdom','London');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('United States of America','Washington, D.C.');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Uruguay','Montevideo');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Uzbekistan','Tashkent');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Vanuatu','Port Vila');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Vatican City (Holy See)','Vatican City');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Venezuela','Caracas');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Vietnam','Hanoi');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Yemen','Sana\'a');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Zambia','Lusaka');
INSERT INTO `countries`.`capital_cities` (`country_name`,`capital_city`) VALUES ('Zimbabwe','Harare');
